### ISSUE TITLE
Game zips Downloading

### ISSUE THREAD

**Issue by techy2493** [XurxoMF/vs-launcher#1]
Hey just wanted to point out there is an existing API for downloading different game versions. The Modmaker application uses it today to download the appropriate game version for comparison against when its creating patch files. You may need to do some decompilation with dnspy,ilspy,dotpeek,rider, etc. to find the right  paths. There is also the anegoStudios repo with an old version of modmaker but I don't know if the newest version has changed that path at all.

**Comment by XurxoMF** [comment]
@techy2493 Hi, the problem here is not that the API is not available. I can download the game from the official website, but there is no .zip option ;-;
