### ISSUE TITLE
Mod folder not used?

### ISSUE THREAD

**Issue by Abby-Pyrrho** [XurxoMF/vs-launcher#13]
When I join a server, the game downloads server mods to ModsByServer and those work just fine.

However, when I put client-side mods in the VSInstallations Mods folder, it doesn't load them into game. I have to put them in the VSGameVersions Mods folder instead of the instance Mods folder for them to load.

Not sure why, because when I click the open folder button using the in-game mod manager, it opens the correct instance Mods folder, so apparently the game somewhat knows that it is the correct folder, but doesn't actually load mods from it.

**Comment by XurxoMF** [comment]
Hi, thx for the report.

Please, send me the `AppData/Roaming/VSLauncher/config.json` and the `AppData/Roaming/VSLauncher/logs/main.log` and tell me the version and installation you're using ^^

Also tell me the mods and versions that are not working and I'll check it out ^^

That's managed by the game, not the launcher, but it may be something wrong so I'll take a look.

**Comment by Abby-Pyrrho** [comment]
[config.json](https://github.com/user-attachments/files/18138230/config.json)
[main.log](https://github.com/user-attachments/files/18138250/main.log)

I just realized, it's actually loading the VintageStoryData folder.

I know that when I used to make shortcuts for different installs, I had to use both --datapath and --addModPath

**Comment by XurxoMF** [comment]
14.12.2024 17:58:49 [Client Notification]     C:\Users\User\AppData\Roaming\VSLGameVersions\1.20.0-rc.3\Mods
14.12.2024 17:58:49 [Client Notification]     C:\Users\User\AppData\Roaming\VintagestoryData\Mods (Not found?)

You're right. It's loading mods from both Game Version folder and VSData folder but not from Installation folder.... this never happend to me before.

I'll fix it and upload a new version with the problem solved.

**Comment by Abby-Pyrrho** [comment]
Oh, thanks! I did copy clientsettings.json from an old installation. I see that line, fixing it now.
