### ISSUE TITLE
Cert Issues

### ISSUE THREAD

**Issue by techy2493** [XurxoMF/vs-launcher#2]
Saw your note about certs on the moddb page. Thought i should share this.

https://letsencrypt.org/

I use this for my own sites very effectively - for free. There is a tool called acme for managing automated cert renewals. It has built in plugins for several of the common hosting techs and a command line interface.

**Comment by XurxoMF** [comment]
@techy2493 Thx for the suggestion.

I'm already using Let's Encrypt on the API Rest but the APP needs a Code Certificate and those can only be bought with a few trusted companies.

It's not an issue but a scary looking warning on install ^^
