### ISSUE TITLE
Linux Support Request

### ISSUE THREAD

**Issue by AllenWu233** [XurxoMF/vs-launcher#3]
The application seems great! Are there any plans for a future Linux release?

**Comment by XurxoMF** [comment]
@AllenWu233 Yes, on the near future. I'll fix a few issues on the current windows version and then start with the Linux compilation.
Ir should not take to much time as I've made the app with a multi os compatible framework so....

**Comment by XurxoMF** [comment]
Check out v0.0.4 and v0.0.5, now with Linux AppImage.

You've to manually install Vintage Story dependencies (like if you downloaded the game directly from client area)... I could only test it on Linux Mint so on other distros it may have bugs.

Check out the wiki on the repo tabs, there is a guide on how to install dependencies if you need it!
