### ISSUE TITLE
Dose not recognise game on another drive

### ISSUE THREAD

**Issue by zackadiax24** [XurxoMF/vs-launcher#4]
I have VS installed onto a different drive (in this case drive G) than drive C, and It is unable to recognize that I even have the game installed.

When I go to create an installation the "select version" box says "no versions found" and I am unable to change it.

For various reasons I do not want to move my game to the C drive.

**Comment by XurxoMF** [comment]
@zackadiax24 The Launcher only recognizes versions installed using the launcher.
I'll add a button so you can choose the folder where your game is installed and add it as a version recognized by the launcher.

**Comment by XurxoMF** [comment]
@zackadiax24 I've uploaded a new version. On the Versions tab you'll find a magnifying glass button. There you can choose the folder where you've tha game installed and it'll add it top the versions list so you can use it on installations ^^

Alse when you add a new installation make sure to select the data folder you were using too. That way you can keep your wolrds and mods.
