### ISSUE TITLE
Credits bug when changing languages

### ISSUE THREAD

**Issue by megabezdelnik** [XurxoMF/vs-launcher#8]
When opening the languages menu, all credits gets replaced with the credit name of current language selected:

![image](https://github.com/user-attachments/assets/a1a8c9f3-d475-4af5-ace2-a44bb7383e6b)

![image](https://github.com/user-attachments/assets/9c384622-66a9-468b-b648-37131c4e4daa)

**Comment by XurxoMF** [comment]
Fixed, it'll show fine on the next update. In a few minutes ^^
